Console.WriteLine("Hmm, hmm, meh, meh");
Console.WriteLine("Mmm, meh, meh, meh, meh");
Console.WriteLine("Hmm, hmm, meh, meh");
Console.WriteLine("Mmm, meh, meh, meh, meh");
Console.WriteLine("Hmm, hmm, meh, meh");
Console.WriteLine("Mmm, meh, meh, meh, meh");
Console.WriteLine("Hmm, hmm, meh, meh");
Console.WriteLine("Mmm, meh, meh, meh, meh");
Console.WriteLine("Then we sleep through day then we play all through the late night");
Console.WriteLine("Sleep through day then we play all through the late night");
Console.WriteLine("Uh, uh, uh, uh, uh, uh, all through the late night");
Console.WriteLine("S'il vous plaît, don't you wait, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("I'm soarin', how the hell did I get in this space?");
Console.WriteLine("Four in the mornin', how did I get in this place?");
Console.WriteLine("Oh it don't matter, got smoke, drink, and I'm runnin' this space");
Console.WriteLine("Done contemplatin', I'ma take it in and groove in this case");
Console.WriteLine("N, N-Dimethyltryptamine and Lysergic acid diethylamide");
Console.WriteLine("The vibes are effervescent, delicious, just how they should be");
Console.WriteLine("N, N-Dimethyltryptamine and Lysergic acid diethylamide");
Console.WriteLine("The vibes are effervescent, delicious, just how they should be");
Console.WriteLine("No sleep in my bed, no sleepin' in my bed");
Console.WriteLine("When we gon' play, gon' play, gon' play until the day");
Console.WriteLine("I said no sleep in my bed, no sleepin' in my bed");
Console.WriteLine("Yeah, we gon' play, gon' play, then we'll sleep all through the day");
Console.WriteLine("And do it again");
Console.WriteLine("Sleep through day then we play all through the late night");
Console.WriteLine("Sleep through day then we play all through the late night");
Console.WriteLine("Uh, uh, uh, uh, uh, uh, all through the late night");
Console.WriteLine("S'il vous plaît, don't you wait, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("Day and night, I toss and turn");
Console.WriteLine("I keep stressin' my mind, mind");
Console.WriteLine("I seek the peace, sometimes I can't restrain");
Console.WriteLine("To join a rage at night, come out and play, play");
Console.WriteLine("Balance, find your balance");
Console.WriteLine("God said it's my talent");
Console.WriteLine("Sprinkle a little season on the salad");
Console.WriteLine("Relieve my heart of malice, hit my palace");
Console.WriteLine("Stroke my cactus, ohh, don't wait");
Console.WriteLine("Don't play (Yea, yea)");
Console.WriteLine("Play no games like the NBA");
Console.WriteLine("Throwin' checks like the NBA");
Console.WriteLine("You a ring, you a ring");
Console.WriteLine("We shootin' shots like the NRA");
Console.WriteLine("Ahh, she jammin' Travis and Kid Cudi");
Console.WriteLine("The new Krayzie Bone and Slim Bun B");
Console.WriteLine("Yeah, shawty, on the scene, pull up on the scene");
Console.WriteLine("Sip my tea, lean no Hennessy");
Console.WriteLine("Ah, save all, take it right");
Console.WriteLine("Ah, take it all, never light");
Console.WriteLine("Ah, had a ball, had a night");
Console.WriteLine("Ah, after all, sleep good");
Console.WriteLine("Sleep through day then we play all through the late night");
Console.WriteLine("Sleep through day then we play all through the late night");
Console.WriteLine("Uh, uh, uh, uh, uh, uh, all through the late night");
Console.WriteLine("S'il vous plaît , don't you wait, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
Console.WriteLine("All through the late night, all through the late night");
